version: "3"

services:  
  graphite:
    image: "dockerhub.aereusdev.com/netric:${TAG}"
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=*.netric.com
        - com.df.servicePath=/
        - com.df.port=80
        - com.df.httpsOnly=true
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      RUN_SETUP_UPDATE: 1
