netric_web:
  build: web/
  ports:
   - "5000:80"
  environment:
     APPLICATION_ENV: development
  volumes:
   - ../server/:/var/www/html/
  links:
   - memcached
   - gearmand
   - mail
   - db1

memcached:
  image: memcached

gearmand:
  image: pataquets/gearmand

db1:
  build: postgres/
  ports:
  - "5432:5432"
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: vagrant

mail:
  build: mail/
  environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: antsystem
  links:
     - db1