version: "3.5"

services:
  netricservice:
    image: dockerhub.aereus.com/netric:${APPLICATION_VER}
    networks:
      - service_netric
      - default
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: ${APPLICATION_VER}
      RUN_SETUP_UPDATE: 1
    ports:
      - 10001:80
    secrets:
      - auth_private_key
      - entityenc
      - anet_key
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role!=manager
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first

  netric_daemon:
    image: dockerhub.aereus.com/netric:${APPLICATION_VER}
    entrypoint: /start-daemon.sh
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: daemon-${APPLICATION_VER}
    secrets:
      - auth_private_key
      - entityenc
      - anet_key
    networks:
      - service_netric
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role!=manager
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first

networks:
  default:
    external: false
  service_netric:
    external: true

secrets:
  entityenc:
    file: /var/aereusdata/secrets/netric/entityenc
    name: entityenc-${APPLICATION_VER}
  auth_private_key:
    file: /var/aereusdata/secrets/netric/auth_private_key
    name: auth_private_key-${APPLICATION_VER}
  anet_key:
    file: /var/aereusdata/secrets/netric/anet_key
    name: anet_key
