version: '2'
services:
  netric_server:
    build: ../
    environment:
      APPLICATION_ENV: testing
    volumes:
      - '../server/tests/tmp:/var/www/html/tests/tmp'
    links:
      - memcached
      - gearmand
      - mail
      - db1
      - mogilefs
      - mogilestore
    depends_on:
      - mofilefs
      - db1
      - gearmand
  memcached:
    image: memcached
  gearmand:
    image: kendu/gearman
  db1:
    image: 'dockerhub.aereusdev.com/pgsql:latest'
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
  mail:
    image: 'dockerhub.aereusdev.com/mail:latest'
    environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: antsystem
      DB_PORT: 5432
    links:
      - db1
    depends_on:
      - db1
  mogilefs:
    image: 'dockerhub.aereusdev.com/mogiletracker:latest'
    environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: mogilefs
      DB_PORT: 5432
      DB_INIT: 'true'
      INIT_STORAGE_HOST: mogilestore
    links:
      - mogilestore
  mogilestore:
    image: 'dockerhub.aereusdev.com/mogilestore:latest'
