version: '2'

services:
  netric_server:
    image: dockerhub.aereusdev.com/netric:latest
    ports:
     - "80:80"
     - "443:443"
    environment:
       APPLICATION_ENV: integration
    links:
     - memcached
     - gearmand
     - mail
     - db1
     - mogilefs
     - mogilestore

  memcached:
    image: memcached

  gearmand:
    image: kendu/gearman

  db1:
    image: dockerhub.aereusdev.com/pgsql:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant

  mail:
    image: dockerhub.aereusdev.com/mail:latest
    environment:
        DB_USER: vagrant
        DB_PASSWORD: vagrant
        DB_HOST: db1
        DB_NAME: antsystem
        DB_PORT: 5432
    links:
    - db1

 c:
    image: dockerhub.aereusdev.com/mogiletracker:latest
    environment:
        DB_USER: vagrant
        DB_PASSWORD: vagrant
        DB_HOST: db1
        DB_NAME: mogilefs
        DB_PORT: 5432
        DB_INIT: "true"
        INIT_STORAGE_HOST: mogilestore
    links:
    - mogilestore

  mogilestore:
    image: dockerhub.aereusdev.com/mogilestore:latest