netric_web:
  build: web/
  ports:
   - "8081:80"
  environment:
     APPLICATION_ENV: development
  volumes:
   - ../server/tests/tmp:/var/www/html/tests/tmp
  links:
   - memcached
   - gearmand
   - mail
   - db1
   - mogilefs
   - mogilestorage

memcached:
  image: memcached

gearmand:
  image: pataquets/gearmand

db1:
  build: postgres/
  ports:
  - "54321:5432"
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: vagrant

mail:
  build: mail/
  environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: antsystem
      DB_PORT: 54321
  links:
  - db1

mogilefs:
  build: mogilefs/
  environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: mogilefs
      DB_PORT: 54321
  links:
  - mogilestorage

mogilestorage:
  build: mogilestorage/
  ports:
    - "7510:7500"
    - "7511:7501"