netric_web:
  build: web/
  ports:
   - "80:80"
  environment:
     APPLICATION_ENV: development
  volumes:
   - ../server/:/var/www/html/
  links:
   - memcached
   - gearmand
   - mail
   - db1
   - mogilefs
   - mogilestore

memcached:
  image: memcached

gearmand:
  image: kendu/gearman

db1:
  build: postgres/
  ports:
  - "5432:5432"
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: vagrant

mail:
  build: mail/
  environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: antsystem
      DB_PORT: 5432
  links:
  - db1

mogilefs:
  build: mogilefs/
  environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: mogilefs
      DB_PORT: 5432
      MGFS_STORE_PORT: 7500
  links:
  - mogilestore

mogilestore:
  build: mogilestore/