version: "3"

services:  
  netric:
    image: "dockerhub.aereusdev.com/netric:latest"
    networks:
      - proxy
      - default
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      RUN_SETUP_UPDATE: 1
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=*.netric.com
        - com.df.servicePath=/
        - com.df.port=80
        - com.df.httpsOnly=true

networks:
  default:
    external: false
  proxy:
    external: true