version: "3.5"

services:
  netricservice:
    image: dockerhub.aereusdev.com/netric:${APPLICATION_VER}
    networks:
      - service_netric
      - default
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: ${APPLICATION_VER}
    ports:
      - 10001:80
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role!=manager
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first

  netric_daemon:
    image: dockerhub.aereusdev.com/netric:${APPLICATION_VER}
    entrypoint: /start-daemon.sh
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: daemon-${APPLICATION_VER}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role!=manager
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first

networks:
  default:
    external: false
  service_netric:
    external: true
