version: "3.4"

services:
  netric_server:
    build:
      context: ../
      target: test
      dockerfile: ./Dockerfile
    environment:
      APPLICATION_ENV: testing
    volumes:
      - "../.reports:/var/www/html/.reports"
    depends_on:
      - memcached
      - gearmand
      - db1
      - objectstorage
    entrypoint: 'bash -c "/netric-setup.sh && composer test > /dev/stdout"'
    logging:
      driver: "json-file"
  memcached:
    image: memcached
  redis:
    image: redis:6
  gearmand:
    image: kendu/gearman
    depends_on:
      - memcached

  db1:
    image: "dockerhub.aereus.com/pgsql:latest"
    command:
      [
        "-c",
        "shared_buffers=256MB",
        "-c",
        "max_connections=200",
        "-c",
        "synchronous_commit=off",
        "-c",
        "fsync=off",
        "-c",
        "full_page_writes=off",
      ]
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: netric
    logging:
      driver: "json-file"

  objectstorage:
    image: dockerhub.aereus.com/objectstoragesvc:latest
    environment:
      - APPLICATION_ENV=devdependency

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      
  notificationpusher:
    image: dockerhub.aereus.com/notificationpushersvc:latest
    ports:
      - "8080:80"
    depends_on:
      - pgsql
    environment:
      - APPLICATION_ENV=development
      - RUN_SETUP_UPDATE=1

  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: notpush
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notificationpusher
