version: "3.5"

services:  
  netric:
    image: dockerhub.aereusdev.com/netric:${APPLICATION_VER}
    networks:
      - proxy
      - default
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: ${APPLICATION_VER}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=*.netric.com
        - com.df.servicePath=/
        - com.df.port=80
        - com.df.httpsOnly=true

  netric_daemon:
    image: dockerhub.aereusdev.com/netric:${APPLICATION_VER}
    entrypoint: /start-daemon.sh
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: daemon-${APPLICATION_VER}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first

networks:
  default:
    external: false
  proxy:
    external: true