version: "3"

services:  
  netric:
    image: "dockerhub.aereusdev.com/netric:v${APPLICATION_VER}"
    networks:
      - proxy
      - default
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: ${APPLICATION_VER}
      RUN_SETUP_UPDATE: 1
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=*.netric.com
        - com.df.servicePath=/
        - com.df.port=80
        - com.df.httpsOnly=true

networks:
  default:
    external: false
  proxy:
    external: true