version: "3.5"

services:  
  netric_daemon:
    image: dockerhub.aereusdev.com/netric:${APPLICATION_VER}
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      APPLICATION_VER: ${APPLICATION_VER}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first