netric_web:
  ports:
   - "80:80"
  environment:
     APPLICATION_ENV: testing
  volumes:
   - ../:/var/www/html/data/log

memcached:
  image: memcached

gearmand:
  image: pataquets/gearmand

db1:
  ports:
  - "54321:5432"
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: vagrant

mail:
  environment:
      DB_USER: vagrant
      DB_PASSWORD: vagrant
      DB_HOST: db1
      DB_NAME: antsystem
      DB_PORT: 54321

mogilefs:
  build: mogilefs/
  environment:
        DB_USER: vagrant
        DB_PASSWORD: vagrant
        DB_HOST: db1
        DB_NAME: mogilefs
        DB_PORT: 54321
  links:
  - mogilestorage

mogilestorage:
  build: mogilestorage/