version: '2'

services:
  netric_server:
    build: ../
    ports:
     - "80:80"
     - "443:443"
    environment:
       APPLICATION_ENV: development
       XDEBUG_CONFIG: "remote_host=${HOST_IP} remote_enable=1 remote_connect_back=1 remote_autostart=1"
    volumes:
     - ../server/:/var/www/html/
    depends_on:
     - elk
    logging:
     driver: gelf
     options:
       gelf-address: "udp://localhost:12201"
    links:
     - memcached
     - gearmand
     - mail
     - db1
     - mogilefs
     - mogilestore
     - elk

  memcached:
    image: memcached

  gearmand:
    image: kendu/gearman

  db1:
    build: postgres/
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
    depends_on:
     - elk
    logging:
     driver: gelf
     options:
       gelf-address: "udp://localhost:12201"

  mail:
    build: mail/
    environment:
        DB_USER: vagrant
        DB_PASSWORD: vagrant
        DB_HOST: db1
        DB_NAME: antsystem
        DB_PORT: 5432
    links:
    - db1

  mogilefs:
    build: mogilefs/
    environment:
        DB_USER: vagrant
        DB_PASSWORD: vagrant
        DB_HOST: db1
        DB_NAME: mogilefs
        DB_PORT: 5432
        MGFS_STORE_PORT: 7500
    links:
    - mogilestore
    logging:
     driver: gelf
     options:
       gelf-address: "udp://localhost:12201"

  mogilestore:
    build: mogilestore/
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  elk:
    build: elk/
    ports:
      - "5601:5601"
      - "9201:9201"
      - "5044:5044"
      - "5000:5000"
      - "12200:12200"
      - "12201:12201/udp"
      - "5141:5141"
      - "5141:5141/udp"

  logstash:
    image: docker pull docker.elastic.co/logstash/logstash:5.4.0
    container_name: logstash
    ports:
          - "12200:12200"
          - "12201:12201/udp"
          - "5141:5141"
          - "5141:5141/udp"


  elastic1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: elastic1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    environment:
        - http.host=0.0.0.0
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"