<?php
namespace NetricApi;

/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Entity query service
 */
interface EntityQueryIf
{
    /**
     * Update the user last active
     * 
     * @param string $userId
     * @param string $accountId
     * @param string $jsonQuery
     * @return string
     * @throws \NetricApi\ErrorException
     * @throws \NetricApi\InvalidArgument
     */
    public function execute($userId, $accountId, $jsonQuery);
}
