<?php
namespace NetricApi;

/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Define what an entity query result will look like
 */
class EntityQueryResultData
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'query_ran',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\NetricApi\EntityQueryData',
        ),
        2 => array(
            'var' => 'account',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'num',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        4 => array(
            'var' => 'total_num',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'entities',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::MAP,
            'elem' => array(
                'type' => TType::MAP,
                'ktype' => TType::STRING,
                'vtype' => TType::STRING,
                'key' => array(
                    'type' => TType::STRING,
                ),
                'val' => array(
                    'type' => TType::STRING,
                    ),
                ),
        ),
    );

    /**
     * @var \NetricApi\EntityQueryData
     */
    public $query_ran = null;
    /**
     * @var string
     */
    public $account = null;
    /**
     * @var int
     */
    public $num = null;
    /**
     * @var int
     */
    public $total_num = null;
    /**
     * @var (array)[]
     */
    public $entities = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['query_ran'])) {
                $this->query_ran = $vals['query_ran'];
            }
            if (isset($vals['account'])) {
                $this->account = $vals['account'];
            }
            if (isset($vals['num'])) {
                $this->num = $vals['num'];
            }
            if (isset($vals['total_num'])) {
                $this->total_num = $vals['total_num'];
            }
            if (isset($vals['entities'])) {
                $this->entities = $vals['entities'];
            }
        }
    }

    public function getName()
    {
        return 'EntityQueryResultData';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->query_ran = new \NetricApi\EntityQueryData();
                        $xfer += $this->query_ran->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->account);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->num);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->total_num);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::LST) {
                        $this->entities = array();
                        $_size0 = 0;
                        $_etype3 = 0;
                        $xfer += $input->readListBegin($_etype3, $_size0);
                        for ($_i4 = 0; $_i4 < $_size0; ++$_i4) {
                            $elem5 = null;
                            $elem5 = array();
                            $_size6 = 0;
                            $_ktype7 = 0;
                            $_vtype8 = 0;
                            $xfer += $input->readMapBegin($_ktype7, $_vtype8, $_size6);
                            for ($_i10 = 0; $_i10 < $_size6; ++$_i10) {
                                $key11 = '';
                                $val12 = '';
                                $xfer += $input->readString($key11);
                                $xfer += $input->readString($val12);
                                $elem5[$key11] = $val12;
                            }
                            $xfer += $input->readMapEnd();
                            $this->entities []= $elem5;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('EntityQueryResultData');
        if ($this->query_ran !== null) {
            if (!is_object($this->query_ran)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('query_ran', TType::STRUCT, 1);
            $xfer += $this->query_ran->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->account !== null) {
            $xfer += $output->writeFieldBegin('account', TType::STRING, 2);
            $xfer += $output->writeString($this->account);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->num !== null) {
            $xfer += $output->writeFieldBegin('num', TType::I32, 3);
            $xfer += $output->writeI32($this->num);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->total_num !== null) {
            $xfer += $output->writeFieldBegin('total_num', TType::I32, 4);
            $xfer += $output->writeI32($this->total_num);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->entities !== null) {
            if (!is_array($this->entities)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('entities', TType::LST, 5);
            $output->writeListBegin(TType::MAP, count($this->entities));
            foreach ($this->entities as $iter13) {
                $output->writeMapBegin(TType::STRING, TType::STRING, count($iter13));
                foreach ($iter13 as $kiter14 => $viter15) {
                    $xfer += $output->writeString($kiter14);
                    $xfer += $output->writeString($viter15);
                }
                $output->writeMapEnd();
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
