<?php
namespace NetricApi;

/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Define query type data
 */
class EntityQueryData
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'obj_type',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'offset',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'limit',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var string
     */
    public $obj_type = null;
    /**
     * @var int
     */
    public $offset = null;
    /**
     * @var int
     */
    public $limit = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['obj_type'])) {
                $this->obj_type = $vals['obj_type'];
            }
            if (isset($vals['offset'])) {
                $this->offset = $vals['offset'];
            }
            if (isset($vals['limit'])) {
                $this->limit = $vals['limit'];
            }
        }
    }

    public function getName()
    {
        return 'EntityQueryData';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->obj_type);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->offset);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->limit);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('EntityQueryData');
        if ($this->obj_type !== null) {
            $xfer += $output->writeFieldBegin('obj_type', TType::STRING, 1);
            $xfer += $output->writeString($this->obj_type);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->offset !== null) {
            $xfer += $output->writeFieldBegin('offset', TType::I32, 2);
            $xfer += $output->writeI32($this->offset);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->limit !== null) {
            $xfer += $output->writeFieldBegin('limit', TType::I32, 3);
            $xfer += $output->writeI32($this->limit);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
